# Generated by Django 3.2.8 on 2021-11-01 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='plan',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='completion_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 1, 9, 42, 24, 624610)),
        ),
    ]
