# Generated by Django 3.2.8 on 2021-11-01 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211101_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='completion_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 1, 9, 50, 47, 436697)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.CharField(max_length=200),
        ),
    ]
