# Generated by Django 3.2.8 on 2021-11-01 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211101_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='total_area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='unit_types',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='completion_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 1, 10, 19, 48, 556668)),
        ),
    ]
