# Generated by Django 3.2.8 on 2021-11-01 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211101_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='bath',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='room',
        ),
        migrations.AlterField(
            model_name='listing',
            name='completion_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 1, 15, 11, 44, 174764)),
        ),
    ]
