# Generated by Django 3.2.8 on 2021-11-02 10:41

import cropperjs.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20211101_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='completion_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 2, 10, 41, 18, 328548)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image',
            field=cropperjs.models.CropperImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cropperjs.models.CropperImageField(null=True, upload_to='')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.listing')),
            ],
        ),
    ]
