# Generated by Django 3.2.8 on 2021-11-02 10:45

import cropperjs.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20211102_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='completion_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 2, 10, 45, 29, 837876)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image',
            field=cropperjs.models.CropperImageField(aspectratio=1.5, null=True, upload_to=''),
        ),
    ]
