# Generated by Django 3.2.8 on 2021-11-02 11:15

import cropperjs.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20211102_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=cropperjs.models.CropperImageField(aspectratio=1.5, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='completion_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 2, 11, 15, 57, 705146)),
        ),
    ]
