# Generated by Django 3.2.8 on 2021-11-02 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20211102_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rera',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='completion_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 2, 12, 51, 5, 847870)),
        ),
    ]
