# Generated by Django 3.2.8 on 2021-11-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20211102_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='completion_date',
        ),
        migrations.AddField(
            model_name='listing',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
