# Generated by Django 3.2.8 on 2021-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20211102_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rera',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
