# Generated by Django 3.2.8 on 2021-11-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_listing_rera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
