# Generated by Django 3.2.10 on 2022-03-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_baseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='plan',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
