# Generated by Django 3.2.10 on 2022-03-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20220322_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
