# Generated by Django 3.2.10 on 2022-04-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_lead_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.stage')),
            ],
        ),
    ]
