# Generated by Django 3.2.10 on 2022-04-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_markleads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyplaces',
            name='place',
            field=models.CharField(max_length=500),
        ),
    ]
