# Generated by Django 3.2.10 on 2022-04-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_nearbyplaces_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='alert',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
