# Generated by Django 3.2.10 on 2022-04-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_listing_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.leadlocation')),
            ],
        ),
    ]
