# Generated by Django 3.2.10 on 2022-04-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_downloadleads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadleads',
            name='loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.leadlocation'),
        ),
    ]
