# Generated by Django 3.2.10 on 2022-04-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_agentaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='occupation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
