# Generated by Django 3.2.10 on 2022-04-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_travelledkms'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelledkms',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
