# Generated by Django 3.2.10 on 2022-04-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcb',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
