# Generated by Django 3.2.10 on 2022-04-21 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_jcb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
