# Generated by Django 3.2.10 on 2022-04-22 12:08

import cropperjs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_alter_reimbursement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jcb',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jcb',
            name='photo',
            field=cropperjs.models.CropperImageField(aspectratio=1.5, blank=True, null=True, upload_to=''),
        ),
    ]
