# Generated by Django 3.2.10 on 2022-05-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_transaction_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='head',
            field=models.TextField(blank=True, null=True),
        ),
    ]
