# Generated by Django 3.2.10 on 2022-05-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_alter_transaction_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expenses', 'Expenses')], max_length=50, null=True),
        ),
    ]
