# Generated by Django 3.2.10 on 2022-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_alter_transaction_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_string', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=50, null=True),
        ),
    ]
