# Generated by Django 3.2.10 on 2022-05-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20220525_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadlist',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
