# Generated by Django 3.2.10 on 2022-05-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(blank=True, default='Discrete', max_length=50, null=True),
        ),
    ]
