# Generated by Django 3.2.10 on 2022-05-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_alter_inventory_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_date', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_type', models.CharField(blank=True, default='Discrete', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
