# Generated by Django 3.2.10 on 2022-06-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstage',
            name='call_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
