# Generated by Django 3.2.10 on 2022-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_notifyemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
