# Generated by Django 3.2.10 on 2022-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_enquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='location_str',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
