# Generated by Django 3.2.10 on 2022-07-30 16:28

import cropperjs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_auto_20220724_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('cus_img', cropperjs.models.CropperImageField(aspectratio=1, null=True, upload_to='')),
                ('cus_name', models.CharField(max_length=50, null=True)),
                ('cus_designation', models.CharField(max_length=50, null=True)),
                ('cus_prod', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
