# Generated by Django 3.2.10 on 2022-07-30 17:56

import cropperjs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction_Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', cropperjs.models.CropperImageField(aspectratio=1.5, null=True, upload_to='')),
                ('text', models.TextField(blank=True, null=True)),
                ('unit_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.booking')),
            ],
        ),
    ]
