# Generated by Django 3.2.10 on 2022-07-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_construction_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction_updates',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
