# Generated by Django 3.2.10 on 2022-07-30 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_alter_construction_updates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction_updates',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
