# Generated by Django 3.2.10 on 2022-07-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_alter_construction_updates_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unit_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
