# Generated by Django 3.2.10 on 2022-08-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_booking_unit_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstage',
            name='call_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
