# Generated by Django 3.2.10 on 2022-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_alter_leadstage_call_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
