# Generated by Django 3.2.10 on 2022-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20221011_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='adset_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='appointment_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='wa_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
