# Generated by Django 3.2.10 on 2022-10-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20221014_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='p_interest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
