# Generated by Django 3.2.10 on 2023-01-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_lead_p_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0, null=True)),
                ('pitch', models.CharField(blank=True, max_length=20, null=True)),
                ('yaw', models.CharField(blank=True, max_length=20, null=True)),
                ('scene_text', models.CharField(blank=True, max_length=20, null=True)),
                ('scene_id', models.CharField(blank=True, max_length=20, null=True)),
                ('scene_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
