# Generated by Django 3.2.10 on 2023-01-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_baseinfo_test_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tour',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
