# Generated by Django 3.2.10 on 2023-01-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_listing_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
