# Generated by Django 3.2.10 on 2023-01-30 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_floorplantype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplantype',
            name='project',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='tp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.floorplantype'),
        ),
    ]
