# Generated by Django 3.2.10 on 2023-01-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20230130_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplantype',
            name='yt_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
