# Generated by Django 3.2.10 on 2023-01-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_alter_floorplan_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplantype',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.listing'),
        ),
    ]
