# Generated by Django 4.1.3 on 2023-05-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0070_floorplantype_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.listing",
                    ),
                ),
            ],
        ),
    ]
