# Generated by Django 4.1.3 on 2023-05-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0072_alter_listing_bathrooms_alter_listing_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
                ("name", models.CharField(max_length=50)),
                ("occ", models.CharField(max_length=50)),
                ("remarks", models.CharField(max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.listing",
                    ),
                ),
            ],
        ),
    ]
