# Generated by Django 4.1.3 on 2023-05-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0074_reviewcard_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="card_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
